site_name: MLPForecast Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - MLPForecast Docs: index.md
  - Tutorial - User Guide:
    - MLPForecast: forecaster.md
    - Model: model.md
    - Net: net.md
    - Evaluation: evaluation.md
    - Metrics: metrics.md