default_language_version:
  python: python3

exclude: ^(poetry.lock|.idea/)

# general checks (see here: https://pre-commit.com/hooks.html)
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.1  # Latest version as of last known update
    hooks:
      - id: poetry-check
     # - id: poetry-lock
     # - id: poetry-export
     # - id: poetry-install

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
      - id: ruff


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-json
      - id: check-ast
        exclude: .vscode
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^LICENSE|\.(html|csv|txt|svg|py)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: \.(html|svg)$
      - id: check-xml
      - id: destroyed-symlinks
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: requirements-txt-fixer


  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  # Sorts Python imports according to the defined style
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]








  # Checks for common security issues in Python code
  #- repo: https://github.com/PyCQA/bandit
  #  rev: 1.7.4
  #  hooks:
  #    - id: bandit

  # Upgrades Python code to newer syntax versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]




  # Removes all unused import statements
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: [--all]

  # Enforces the usage of the Commitizen commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]



  # Performs commit message validation.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: no-commit-to-branch
