default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly

# general checks (see here: https://pre-commit.com/hooks.html)
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.1  # Latest version as of last known update
    hooks:
      - id: poetry-check
     # - id: poetry-lock
     # - id: poetry-export
     # - id: poetry-install


  - repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
      - id: sync-pre-commit-deps

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
      - id: ruff


  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        language: python
        exclude: 'poetry.lock'  # Exclude the poetry.lock file



  # Sorts Python imports according to the defined style
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]


  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake


  # flake8 formatting
  #- repo: https://github.com/pycqa/flake8
  #  rev: 7.1.0
  # hooks:
  #    - id: flake8
        #args:
        #  - "--max-line-length=128"

  #- repo: https://github.com/hhatto/autopep8
  #  rev: v2.3.1  # select the tag or revision you want, or run `pre-commit autoupdate`
  #  hooks:
  #    - id: autopep8



  # Checks for common security issues in Python code
  #- repo: https://github.com/PyCQA/bandit
  #  rev: 1.7.4
  #  hooks:
  #    - id: bandit

  # Upgrades Python code to newer syntax versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  # Automatically removes unnecessary # noqa comments
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies: &flake8_deps
          - flake8-bugbear==22.8.23
          - flake8-comprehensions==3.10.0
          - flake8-docstrings==1.6.0

  # Removes all unused import statements
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: [--all]

  # Enforces the usage of the Commitizen commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]

  # Performs commit message validation.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: no-commit-to-branch



  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
        exclude: .vscode
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-toml
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace  # Corrected indentation here
