from __future__ import annotations
import logging
import joblib
import os
from pathlib import Path
from timeit import default_timer
import pandas as pd
import numpy as np
from mlpforecast.forecaster.utils import format_target
from mlpforecast.evaluation.metrics import evaluate_point_forecast

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("RegForecaster")


class BasicForecast:
    """
    PytorchForecast class for setting up and managing the training process of a PyTorch model using PyTorch Lightning.

    Attributes
    ----------
        exp_name (str): The name of the experiment.
        file_name (str): The name of the file to save the logs and model checkpoints.
        seed (int): The seed for random number generation to ensure reproducibility.
        root_dir (str): The root directory for saving logs and checkpoints.
        trial (optuna.trial.Trial): Optuna trial for hyperparameter optimization.
        metric (str): The metric to monitor for early stopping and model checkpointing.
        max_epochs (int): The maximum number of training epochs.
        wandb (bool): Flag to use Wandb logger instead of TensorBoard logger.
        rich_progress_bar (bool): Flag to use rich progress bar for training visualization.
    """

    def __init__(
        self,
        exp_name="Tanesco",
        file_name=None,
        seed=42,
        root_dir="../",
        trial=None,
        metric="val_mae",
        model_type="MLPF"
    ):
        """
        Initializes the PytorchForecast class with the given parameters.

        Args:
            exp_name (str): The name of the experiment. Defaults to "Tanesco".
            file_name (str): The name of the file to save the logs and model checkpoints. Defaults to None.
            seed (int): The seed for random number generation. Defaults to 42.
            root_dir (str): The root directory for saving logs and checkpoints. Defaults to "../".
            trial (optuna.trial.Trial): Optuna trial for hyperparameter optimization. Defaults to None.
            metric (str): The metric to monitor for early stopping and model checkpointing. Defaults to "val_mae".
            max_epochs (int): The maximum number of training epochs. Defaults to 10.
            wandb (bool): Flag to use Wandb logger instead of TensorBoard logger. Defaults to False.
            rich_progress_bar (bool): Flag to use rich progress bar for training visualization. Defaults to True.
        """
        super().__init__()

        self.exp_name = exp_name
        self.file_name = file_name
        self.seed = seed
        self.root_dir = root_dir
        self.trial = trial
        self.metric = metric
        self.model_type = model_type
        self.model = None
        self.train_df=None
        self.datamodule = None
        self._create_folder()


    def _create_folder(self):
        """
        Creates directories for storing the results, logs, and figures generated by the model.
        """
        self.results_path = Path(f"{self.root_dir}/results/{self.exp_name}/{self.model_type}/")

        self.logs = Path(f"{self.root_dir}/logs/{self.exp_name}/{self.model_type}/")
        self.figures = Path(f"{self.root_dir}/figures/{self.exp_name}/{self.model_type}/")
        self.figures.mkdir(parents=True, exist_ok=True)
        self.logs.mkdir(parents=True, exist_ok=True)
        self.results_path.mkdir(parents=True, exist_ok=True)
        if self.file_name is not None:
            self.checkpoints = Path(f"{self.root_dir}/checkpoints/{self.exp_name}/{self.model_type}/{self.file_name}")
        else:
            self.checkpoints = Path(f"{self.root_dir}/checkpoints/{self.exp_name}/{self.model_type}")
        self.checkpoints.mkdir(parents=True, exist_ok=True)


    def on_save_checkpoint(self):
        """
        Save the data pipeline to a file and add the file path to the checkpoint dictionary.

        Args:
            checkpoint (dict): Checkpoint dictionary.
        """
        # Save the pipeline and model into a dictionary
        save_dict = {
            'model': self.model.model,
            'data_pipeline': self.model.data_pipeline
        }
        joblib.dump(save_dict, f"{self.checkpoints}/model_and_pipeline.pkl")
        
    def on_load_checkpoint(self):
        """
        Load the data pipeline from a file.

        Args:
            checkpoint (dict): Checkpoint dictionary.
        """
        model_path=[str(file) for file in self.checkpoints.glob('*') if file.is_file()][-1]
        if os.path.exists(model_path):
            model_data_pipeline = joblib.load(model_path)
            self.model.model = model_data_pipeline['model']
            self.model.data_pipeline = model_data_pipeline['data_pipeline']
        else:
            raise FileNotFoundError(f"Checkpoint file not found: {model_path}")


    def fit(
        self,
        train_df,
        val_df=None,
        train_ratio=1.0,
    ):
        """
        Fit the model using the provided training DataFrame.

        Args:
            train_df (pd.DataFrame): The training data.
            val_df (pd.DataFrame, optional): The validation data. If None, will split train_df based on train_ratio.
            train_ratio (float, optional): Proportion of data to use for training. Default is 0.80.
            drop_last (bool, optional): Whether to drop the last incomplete batch. Default is True.
        Returns:
            (float): The training wall time or cost metric based on the training configuration.

        Raises
        ------
            ValueError: If the model instance is not initialized.
        """
        # Check if the model instance is initialized
        if self.model is None:
            raise ValueError("Model instance is empty")

        # Set the checkpoint path for the model
        self.model.checkpoint_path = self.checkpoints

        # Fit the data pipeline using the training DataFrame
        self.model.data_pipeline.fit(train_df.copy())

        # If no validation DataFrame is provided, split the training DataFrame

        if val_df is None and (train_ratio!=1.0):
            self.train_df = train_df.copy()
            train_df, val_df = (
                train_df.iloc[: int(train_ratio * len(train_df))],
                train_df.iloc[int(train_ratio * len(train_df)) :],
            )

            val_feature, val_target = self.model.data_pipeline.transform(val_df)
        
        elif val_df is not None:
            val_feature, val_target = self.model.data_pipeline.transform(val_df)
            self.train_df = pd.concat([train_df.copy(), val_df.copy()], axis=0)
        else:
            val_feature, val_target = None, None
            self.train_df = train_df.copy()
            
        
        
        # Transform the training data into features and targets
        train_feature, train_target = self.model.data_pipeline.transform(train_df)


        # Sort the training DataFrame by the specified date column
        self.train_df = self.train_df.sort_values(by=self.model.data_pipeline.date_column)

        # Select the last 'max_data_drop' rows plus 'input_window_size' rows
        data_drop = self.model.data_pipeline.max_data_drop
        input_window = self.model.data_pipeline.input_window_size

        self.train_df = self.train_df.iloc[-(data_drop + input_window) :]

        # Set up the trainer
        start_time = default_timer()
        logger.info("""---------------Training started ---------------------------""")

        # Train the model and log training duration
        self.model.fit(train_feature, train_target)
        self.train_walltime = default_timer() - start_time
        logging.info(f"Training complete after {self.train_walltime / 60:.2f} minutes")
        self.on_save_checkpoint()
    

        if self.trial is not None:
            # Make predictions and compute the cost metric for hyper-param optimisation
            _, metrics=self.evaluate(val_df, daily_feature=False)
            cost = metrics.groupby("target")["SMAPE(%)"].median().iloc[-1].round(2)
            return cost
        else:
            return self.train_walltime
        

    

    def load_and_prepare_data(self, test_df: pd.DataFrame, daily_feature: str):
        """
        Loads the checkpoint and prepares the ground truth data.
        
        Args:
            test_df (pd.DataFrame): The test DataFrame containing the input features for prediction.
            daily_feature (str): The daily feature to use in the model.

        Returns:
            ground_truth (pd.DataFrame): A DataFrame containing the ground truth data.
        """
        self.on_load_checkpoint()
        self.model.data_pipeline.daily_features = daily_feature

        # Prepare ground truth data
        if self.train_df is not None:
            ground_truth = test_df.iloc[self.model.data_pipeline.max_data_drop :].copy()
        ground_truth[self.model.data_pipeline.date_column] = pd.to_numeric(
            ground_truth[self.model.data_pipeline.date_column]
        )
        return ground_truth


    def perform_prediction(self, features: np.array):
        """
        Performs the model prediction.
        
        Args:
            features (np.array): numpy array containing the input features for prediction.

        Returns:
            (dict): A dictionary containing the forecasted values.
        
        """

        start_time = default_timer()
        output = self.model.forecast(features)
        self.test_walltime = default_timer() - start_time
        
        return output


    def create_results_df(
        self, time_stamp, ground_truth, predictions, target_series, date_column
    ):
        """
        Creates a DataFrame with the timestamp index and populates it with ground truth and forecasted values.
        
        Args:
            time_stamp (np.array): The timestamp index.
            ground_truth (np.array): The ground truth values.
            predictions (np.array): The forecasted values.
            target_series (list): A list of target series names.
            date_column (str): The name of the date column.

        Returns:
            results_df (pd.DataFrame): A DataFrame containing the ground truth and forecasted values, indexed by timestamp.
        
        """
        results_df = pd.DataFrame(index=pd.to_datetime(time_stamp.flatten(), unit="ns"))
        results_df.index.name = date_column

        for target_idx, target_name in enumerate(target_series):
            results_df[target_name] = ground_truth[:, :, target_idx].flatten()
            results_df[f"{target_name}_forecast"] = predictions[:, :, target_idx].flatten()

        return results_df


    def evaluate_point_forecast(self, ground_truth, pred, time_stamp):
        """
        Evaluates the point forecast.

        Args:
            ground_truth (np.array): The ground truth values.
            pred (np.array): The forecasted values.
            time_stamp (np.array): The timestamp index.

        Returns:
            (dict): A dictionary containing the evaluation metrics.
        
        """
        return evaluate_point_forecast({
            "true": ground_truth,
            "loc": pred,
            "index": time_stamp,
            "targets": self.model.data_pipeline.target_series,
        })
    
    def get_ground_truth(self, 
                       test_df=None,  
                       daily_feature=True):
        
        ground_truth = self.load_and_prepare_data(test_df, daily_feature)
        time_stamp = ground_truth[[self.model.data_pipeline.date_column]].values
        ground_truth = ground_truth[self.model.data_pipeline.target_series].values

        time_stamp = format_target(
            time_stamp,
            self.model.data_pipeline.input_window_size,
            self.model.data_pipeline.forecast_horizon,
            daily_feature=self.model.data_pipeline.daily_features,
        )
        ground_truth = format_target(
            ground_truth,
            self.model.data_pipeline.input_window_size,
            self.model.data_pipeline.forecast_horizon,
            daily_feature=self.model.data_pipeline.daily_features,
        )

        return time_stamp, ground_truth
    
    def format_test_df(self, test_df=None):
        data_drop = self.model.data_pipeline.max_data_drop
        input_window = self.model.data_pipeline.input_window_size
        if self.train_df is not None:
            initial_test_df=self.train_df.iloc[-(data_drop + input_window) :].copy()
        elif test_df is not None and self.train_df is not None:
            test_df = pd.concat([initial_test_df, test_df], axis=0)
        elif test_df is  None and self.train_df is not None:
            test_df = initial_test_df
        else:
            raise ValueError("You can not call prediction without specifying test-data")
        test_df = test_df.sort_values(by=self.model.data_pipeline.date_column)
        return test_df
    
    def predict(self, test_df=None, covariate_df=None, daily_feature=True):
        self.on_load_checkpoint()
        
        test_df = self.format_test_df(test_df)
        self.model.data_pipeline.daily_features=daily_feature
        features, _ = self.model.data_pipeline.transform(test_df.copy())
        output=self.perform_prediction(features)
        N, T, C = output["loc"].shape

        scaler = self.model.data_pipeline.data_pipeline.named_steps["scaling"]
        target_scaler = scaler.named_transformers_["target_scaler"]
        output["loc"] = target_scaler.inverse_transform(output["loc"].reshape(N * T, C))
        output["loc"] = output["loc"].reshape(N, T, C)

        return output

    def evaluate(self, test_df=None, covariate_df=None, daily_feature=True):
        """
        Perform prediction on the test DataFrame and return a DataFrame with ground truth and forecasted values.

        Args:
            test_df (pd.DataFrame): The test DataFrame containing the input features for prediction.
            daily_feature (bool): Flag indicating whether daily features are used in the model. Default is True.

        Returns
        -------
            pd.DataFrame: A DataFrame containing the ground truth and forecasted values, indexed by timestamp.
        """
        output=self.predict(test_df, covariate_df, daily_feature) 
        time_stamp, ground_truth = self.get_ground_truth(test_df=test_df, 
                                                         daily_feature=daily_feature)
        # Assert that the prediction and ground truth shapes are the same
        if output["loc"].shape != ground_truth.shape:
            raise ValueError("Shape mismatch: loc and ground_truth must have the same shape.")
      

        # Evaluate point forecast
        metrics_df = self.evaluate_point_forecast(ground_truth, output["loc"], time_stamp)
        metrics_df["test-time"] = self.test_walltime
        metrics_df["Model"] = self.model_type.upper()

        
        # Create results DataFrame
        results_df = self.create_results_df(
            time_stamp,
            ground_truth,
            output["loc"],
            self.model.data_pipeline.target_series,
            self.model.data_pipeline.date_column,
        )
        results_df["Model"] = self.model_type.upper()

        return results_df, metrics_df

